# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ivan Taxi â€” telegram bot for Uber
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A telegram bot that gets you an uber, where you need it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: rulikkk
github_username:  rulikkk

# Build settings
markdown: kramdown
